import { MediaItem, MediaType, Image } from '../models/media.model';
import { Project, ProjectId, ProjectLocation } from '../models/project.model';

export class DataStore {
  static allMedia: MediaItem[] = [
    <Image>{
      projectId: ProjectId.IceCave,
      type: MediaType.Image,
      src: 'assets/img/icecave.png',
      thumbSrc: 'assets/img/thumb/icecave-300.png',
      alt: 'Ice cave in the desert',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.Christmas2020,
      type: MediaType.Image,
      src: 'assets/img/tort-tube.png',
      thumbSrc: 'assets/img/thumb/tort-tube-300.png',
      alt: 'Tortoise on floor of london underground train',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.Christmas2020,
      type: MediaType.Image,
      src: 'assets/img/tort-shop.png',
      thumbSrc: 'assets/img/thumb/tort-shop-300.png',
      alt: 'Tortoise on shop floor',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.WhatNow,
      type: MediaType.Image,
      src: 'assets/img/what-now.png',
      thumbSrc: 'assets/img/thumb/what-now-300.png',
      alt: 'Toolbox that says "What now?"',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.Dosist,
      type: MediaType.Image,
      src: 'assets/img/dosist7.png',
      thumbSrc: 'assets/img/thumb/dosist7-300.png',
      alt: 'Arrangement of Dosist products',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.NewBalance,
      type: MediaType.Image,
      src: 'assets/img/new-balance.jpg',
      thumbSrc: 'assets/img/thumb/new-balance-300.jpg',
      alt: 'New Balance shoe with unique fabric pattern',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.ReggieRobot,
      type: MediaType.Image,
      src: 'assets/img/robot-fjord.png',
      thumbSrc: 'assets/img/thumb/robot-fjord-300.png',
      alt: 'Giant robot standing over a fjord',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.ReggieRobot,
      type: MediaType.Image,
      src: 'assets/img/robot-double.png',
      thumbSrc: 'assets/img/thumb/robot-double-300.png',
      alt: 'Two versions of a toy robot',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.EsteeLauder,
      type: MediaType.Image,
      src: 'assets/img/estee-lauder.png',
      thumbSrc: 'assets/img/thumb/estee-lauder-300.png',
      alt: 'Estee Lauder products',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaAccord,
      type: MediaType.Image,
      src: 'assets/img/accord-2.png',
      thumbSrc: 'assets/img/thumb/accord-2-300.png',
      alt: 'Honda Accord seat',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaAccord,
      type: MediaType.Image,
      src: 'assets/img/accord-7.png',
      thumbSrc: 'assets/img/thumb/accord-7-300.png',
      alt: 'Honda Accord wheel',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaAccord,
      type: MediaType.Image,
      src: 'assets/img/accord-1.png',
      thumbSrc: 'assets/img/thumb/accord-1-300.png',
      alt: 'Honda Accord side profile',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaAccord,
      type: MediaType.Image,
      src: 'assets/img/accord-3.png',
      thumbSrc: 'assets/img/thumb/accord-3-300.png',
      alt: 'Honda Accord wheel close up',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.Acadia,
      type: MediaType.Image,
      src: 'assets/img/brain-transform.png',
      thumbSrc: 'assets/img/thumb/brain-transform-300.png',
      alt: 'Metaphorical image of a hallucinations disappearing in a brain ',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaCRV,
      type: MediaType.Image,
      src: 'assets/img/honda-crv1.jpg',
      thumbSrc: 'assets/img/thumb/honda-crv1-300.jpg',
      alt: 'Image of a Honda CRV car boot ',
      includeInGallery: true,
    },
    <Image>{
      projectId: ProjectId.HondaCRV,
      type: MediaType.Image,
      src: 'assets/img/honda-crv2.png',
      thumbSrc: 'assets/img/thumb/honda-crv2-300.png',
      alt: 'Image of a Honda CRV car dashboard ',
      includeInGallery: true,
    },
    <Image>{
        projectId: ProjectId.HondaCoupe,
        type: MediaType.Image,
        src: 'assets/img/honda-coupe-1.png',
        thumbSrc: 'assets/img/thumb/honda-coupe-1-300.png',
        alt: 'Image of a Honda Civic Coupe front seat ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaCoupe,
        type: MediaType.Image,
        src: 'assets/img/honda-coupe-2.png',
        thumbSrc: 'assets/img/thumb/honda-coupe-2-300.png',
        alt: 'Image of a Honda Civic Coupe back seat ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaCoupe,
        type: MediaType.Image,
        src: 'assets/img/honda-coupe-3.png',
        thumbSrc: 'assets/img/thumb/honda-coupe-3-300.png',
        alt: 'Image of a Honda Civic Coupe gear stick ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-1.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-1-300.png',
        alt: 'Image of a Honda Civic Sedan sunroof ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-2.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-2-300.png',
        alt: 'Image of a Honda Civic Sedan folded backseat ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-1.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-1-300.png',
        alt: 'Image of a Honda Civic Sedan fo ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-12.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-12-300.png',
        alt: 'Image of a Honda Civic Sedan cream seats ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-10.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-10-300.png',
        alt: 'Image of a Honda Civic Sedan grey seats ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-8.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-8-300.png',
        alt: 'Image of a Honda Civic Sedan black seats ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSedan,
        type: MediaType.Image,
        src: 'assets/img/honda-sedan-7.png',
        thumbSrc: 'assets/img/thumb/honda-sedan-7-300.png',
        alt: 'Image of a Honda Civic Sedan back seats ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.HondaSensing,
        type: MediaType.Image,
        src: 'assets/img/honda-sensing.png',
        thumbSrc: 'assets/img/thumb/honda-sensing-300.png',
        alt: 'Image of a Honda car sensing system ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.AlexiaFarm,
        type: MediaType.Image,
        src: 'assets/img/potato.png',
        thumbSrc: 'assets/img/thumb/potato-300.png',
        alt: 'Image of a hand pulling potatoes from the earth ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.PocketCamera,
        type: MediaType.Image,
        src: 'assets/img/folding-camera.png',
        thumbSrc: 'assets/img/thumb/folding-camera-300.png',
        alt: 'A camera that folds ',
        includeInGallery: true,
      },
      <Image>{
        projectId: ProjectId.Scorpion,
        type: MediaType.Image,
        src: 'assets/img/scorpion.png',
        thumbSrc: 'assets/img/thumb/scorpion-300.png',
        alt: 'Image of an animated, metallic scorpion',
        includeInGallery: true,
      },
  ];

  static allProjects: Project[] = [
    {
      id: ProjectId.IceCave,
      yearWorkedOn: 2018,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Ice Cave',
      description: 'A project for a client to create an ice cave in a desert.',
    },
    {
      id: ProjectId.Christmas2020,
      yearWorkedOn: 2020,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Saddington Baynes Christmas 2020',
      description:
        'The Christmas card by Saddington Baynes in 2020 was a recap of each month of the events of 2020 from the perspective of a tortoise. ',
    },
    {
      id: ProjectId.WhatNow,
      yearWorkedOn: 2020,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'What Now?',
      description:
        'I modelled and textured the toolbox and its contents, as well as lighting and rendering the final image at 12k resolution. The toolbox was made using Maya, zBrush, and Substance Painter, and was rendered using Vray.',
    },
    {
      id: ProjectId.Dosist,
      yearWorkedOn: 2020,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Dosist',
      description:
        'The products for this campaign were modelled from real life reference rather than using CAD data, measuring and modelling to ensure they were accurate. This was done in Maya, and then textured to ensure a realistic, natural paper feel.',
    },
    {
      id: ProjectId.NewBalance,
      yearWorkedOn: 2020,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'New Balance',
      description:
        "This project was done to learn how to use Substance Designer and realise it's potential for creating unique fabric patterns.",
    },
    {
      id: ProjectId.ReggieRobot,
      yearWorkedOn: 2019,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Reggie the Robot',
      description:
        'Reggie the Robot was first created as part of a series of images of classic childhood toys living in the real world. Once the character was created, he was then used as the Saddington Baynes mascot and has featured in various RnD pieces since.',
    },
    {
      id: ProjectId.EsteeLauder,
      yearWorkedOn: 2019,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Estée Lauder - RnD',
      description:
        'This image was created as part of an RnD project to demonstrate the power of CGI to create product imagery for beauty campaigns. ',
    },
    {
      id: ProjectId.HondaAccord,
      yearWorkedOn: 2017,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Honda Accord',
      description:
        'For the Honda Accord I was lighting and rendering the shots below, as well as adjusting shaders when necessary for a shot. Additionally to this I lit and rendered animations that could be seamlessly linked together in different sequences.',
    },
    {
      id: ProjectId.Acadia,
      yearWorkedOn: 2016,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'ACADIA - Transform the Brain',
      description:
        "This was an advertisement created to demonstrate the confusing and overwhelming hallucinations caused by Parkinson's Disease, which are subsequently reduced by the drug produced by ACADIA. For this project, I textured various assets such as the snake, bugs and the girl in a vivid and other-worldly manner.",
    },
    {
      id: ProjectId.HondaCRV,
      yearWorkedOn: 2017,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Honda C-RV',
      description:
        'For the C-RV I lit location and studio images, as well as modelling and prepping props required for the shots.',
    },
    {
      id: ProjectId.HondaCoupe,
      yearWorkedOn: 2017,
      location: ProjectLocation.SaddingtonBaynes,
      title: 'Honda C-RV',
      description:
        'For the C-RV I lit location and studio images, as well as modelling and prepping props required for the shots.',
    },
  ];
}
